### ISSUE TITLE
Test wanted for feature `srcinfo` and example `printsrcinfo`

### ISSUE THREAD

**Issue by 7Ji** [7Ji/pkgbuild-rs#2]
@Integral-Tech @hbiyik @wyf9661 @ericwoud @kwankiu @Joffr3y 

(Sorry for the ping, I'm sending this to any one I know that enjoys Arch and has experience on maintaining their PKGBUILDs, if you don't have free time, you can ignore this).

I've added the `srcinfo` feature, and made sure the example binary `printsrcinfo` generates a same output as `makepkg --printsrcinfo` (with some differences due to strongly-typed `Pkgbuild` type). 

This would greatly improve the efficiency of PKGBUILD development. For `kodi-nexus-mpp-git`, instead of the 4.65 seconds took by `makepkg --printsrcinfo`, the `printsrcinfo` example here only takes 0.017 seconds.

But, as everything written from scratch, this needs broader, real-world tests.

Please help test the feature and the example binary, you can build it as follows:
```
git clone https://github.com/7Ji/pkgbuild-rs
cd pkgbuild-rs
cargo build --release --features srcinfo --example printsrcinfo 
strip target/release/examples/printsrcinfo -o ~/bin/printsrcinfo
```
And run `~/bin/printsrcinfo` instead of `makepkg --printsrcinfo`

**Comment by hbiyik** [comment]
i had noticed that there is actually a significant delay eachtime makepkg is invoked, ie, below script directly includes the shell libraries to generate srcinfo

test.sh
```shell
source /usr/share/makepkg/srcinfo.sh
source PKGBUILD
write_srcinfo
```
 and `time ./test.sh > /dev/null` executes in 0.7 seconds, nowhere near the rust but miles faster than original 4.5s of makepkg.

tested on 3588.
